version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "13"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "php"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/reza-cyber77/BookStack"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "ember",
    "vue",
    "react",
    "angular",
    "meteor",
    "angularjs"
  ]

[[analyzers]]
name = "docker"

[[analyzers]]
name = "ansible"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "yapf"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "rustfmt"

[[transformers]]
name = "php-cs-fixer"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "standardrb"

[[transformers]]
name = "dotnet-format"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "gofmt"